name: 'ember-cli-code-coverage check'
description: 'Find out how much of a change to your code coverage size a PR will have'
author: 'Francesco Novy'
branding:
  icon: 'bar-chart-2'
  color: 'orange'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
  test-command:
    description: 'The command to run your tests'
    default: 'yarn test-coverage'
  coverage-file:
    description: 'The location of coverage summary.json file'
    default: './coverage/coverage-summary.json'
  coverage-indicator:
    description: 'The coverage type to use. One of: statements, lines, functions, branches'
    default: 'statements'
  working-directory:
    description: 'Ember app directory'
    default: './'
  message:
    description: 'Comment message title that will be posted on PR'
    default: 'Test coverage: **{testCoverage}%**'
runs:
  using: 'node16'
  main: 'index.js'
